// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.36.1
// source: etg_common.proto

package peerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompressionAlgoPb int32

const (
	CompressionAlgoPb_Invalid CompressionAlgoPb = 0
	CompressionAlgoPb_None    CompressionAlgoPb = 1
	CompressionAlgoPb_Zstd    CompressionAlgoPb = 2
)

// Enum value maps for CompressionAlgoPb.
var (
	CompressionAlgoPb_name = map[int32]string{
		0: "Invalid",
		1: "None",
		2: "Zstd",
	}
	CompressionAlgoPb_value = map[string]int32{
		"Invalid": 0,
		"None":    1,
		"Zstd":    2,
	}
)

func (x CompressionAlgoPb) Enum() *CompressionAlgoPb {
	p := new(CompressionAlgoPb)
	*p = x
	return p
}

func (x CompressionAlgoPb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionAlgoPb) Descriptor() protoreflect.EnumDescriptor {
	return file_etg_common_proto_enumTypes[0].Descriptor()
}

func (CompressionAlgoPb) Type() protoreflect.EnumType {
	return &file_etg_common_proto_enumTypes[0]
}

func (x CompressionAlgoPb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionAlgoPb.Descriptor instead.
func (CompressionAlgoPb) EnumDescriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{0}
}

type NatType int32

const (
	NatType_Unknown          NatType = 0
	NatType_OpenInternet     NatType = 1
	NatType_NoPAT            NatType = 2
	NatType_FullCone         NatType = 3
	NatType_Restricted       NatType = 4
	NatType_PortRestricted   NatType = 5
	NatType_Symmetric        NatType = 6
	NatType_SymUdpFirewall   NatType = 7
	NatType_SymmetricEasyInc NatType = 8
	NatType_SymmetricEasyDec NatType = 9
)

// Enum value maps for NatType.
var (
	NatType_name = map[int32]string{
		0: "Unknown",
		1: "OpenInternet",
		2: "NoPAT",
		3: "FullCone",
		4: "Restricted",
		5: "PortRestricted",
		6: "Symmetric",
		7: "SymUdpFirewall",
		8: "SymmetricEasyInc",
		9: "SymmetricEasyDec",
	}
	NatType_value = map[string]int32{
		"Unknown":          0,
		"OpenInternet":     1,
		"NoPAT":            2,
		"FullCone":         3,
		"Restricted":       4,
		"PortRestricted":   5,
		"Symmetric":        6,
		"SymUdpFirewall":   7,
		"SymmetricEasyInc": 8,
		"SymmetricEasyDec": 9,
	}
)

func (x NatType) Enum() *NatType {
	p := new(NatType)
	*p = x
	return p
}

func (x NatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NatType) Descriptor() protoreflect.EnumDescriptor {
	return file_etg_common_proto_enumTypes[1].Descriptor()
}

func (NatType) Type() protoreflect.EnumType {
	return &file_etg_common_proto_enumTypes[1]
}

func (x NatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NatType.Descriptor instead.
func (NatType) EnumDescriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{1}
}

type RpcDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainName  string `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	ProtoName   string `protobuf:"bytes,2,opt,name=proto_name,json=protoName,proto3" json:"proto_name,omitempty"`
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodIndex uint32 `protobuf:"varint,4,opt,name=method_index,json=methodIndex,proto3" json:"method_index,omitempty"`
}

func (x *RpcDescriptor) Reset() {
	*x = RpcDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcDescriptor) ProtoMessage() {}

func (x *RpcDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcDescriptor.ProtoReflect.Descriptor instead.
func (*RpcDescriptor) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{0}
}

func (x *RpcDescriptor) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *RpcDescriptor) GetProtoName() string {
	if x != nil {
		return x.ProtoName
	}
	return ""
}

func (x *RpcDescriptor) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RpcDescriptor) GetMethodIndex() uint32 {
	if x != nil {
		return x.MethodIndex
	}
	return 0
}

type RpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Descriptor_ *RpcDescriptor `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Request     []byte         `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	TimeoutMs   int32          `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{1}
}

func (x *RpcRequest) GetDescriptor_() *RpcDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *RpcRequest) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RpcRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type RpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response  []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Error     *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RuntimeUs uint64 `protobuf:"varint,3,opt,name=runtime_us,json=runtimeUs,proto3" json:"runtime_us,omitempty"`
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{2}
}

func (x *RpcResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RpcResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RpcResponse) GetRuntimeUs() uint64 {
	if x != nil {
		return x.RuntimeUs
	}
	return 0
}

type RpcCompressionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algo         CompressionAlgoPb `protobuf:"varint,1,opt,name=algo,proto3,enum=easytier_go.common.CompressionAlgoPb" json:"algo,omitempty"`
	AcceptedAlgo CompressionAlgoPb `protobuf:"varint,2,opt,name=accepted_algo,json=acceptedAlgo,proto3,enum=easytier_go.common.CompressionAlgoPb" json:"accepted_algo,omitempty"`
}

func (x *RpcCompressionInfo) Reset() {
	*x = RpcCompressionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCompressionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCompressionInfo) ProtoMessage() {}

func (x *RpcCompressionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCompressionInfo.ProtoReflect.Descriptor instead.
func (*RpcCompressionInfo) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{3}
}

func (x *RpcCompressionInfo) GetAlgo() CompressionAlgoPb {
	if x != nil {
		return x.Algo
	}
	return CompressionAlgoPb_Invalid
}

func (x *RpcCompressionInfo) GetAcceptedAlgo() CompressionAlgoPb {
	if x != nil {
		return x.AcceptedAlgo
	}
	return CompressionAlgoPb_Invalid
}

type RpcPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromPeer        uint32              `protobuf:"varint,1,opt,name=from_peer,json=fromPeer,proto3" json:"from_peer,omitempty"`
	ToPeer          uint32              `protobuf:"varint,2,opt,name=to_peer,json=toPeer,proto3" json:"to_peer,omitempty"`
	TransactionId   int64               `protobuf:"varint,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Descriptor_     *RpcDescriptor      `protobuf:"bytes,4,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Body            []byte              `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	IsRequest       bool                `protobuf:"varint,6,opt,name=is_request,json=isRequest,proto3" json:"is_request,omitempty"`
	TotalPieces     uint32              `protobuf:"varint,7,opt,name=total_pieces,json=totalPieces,proto3" json:"total_pieces,omitempty"`
	PieceIdx        uint32              `protobuf:"varint,8,opt,name=piece_idx,json=pieceIdx,proto3" json:"piece_idx,omitempty"`
	TraceId         int32               `protobuf:"varint,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CompressionInfo *RpcCompressionInfo `protobuf:"bytes,10,opt,name=compression_info,json=compressionInfo,proto3" json:"compression_info,omitempty"`
}

func (x *RpcPacket) Reset() {
	*x = RpcPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPacket) ProtoMessage() {}

func (x *RpcPacket) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcPacket.ProtoReflect.Descriptor instead.
func (*RpcPacket) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{4}
}

func (x *RpcPacket) GetFromPeer() uint32 {
	if x != nil {
		return x.FromPeer
	}
	return 0
}

func (x *RpcPacket) GetToPeer() uint32 {
	if x != nil {
		return x.ToPeer
	}
	return 0
}

func (x *RpcPacket) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *RpcPacket) GetDescriptor_() *RpcDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *RpcPacket) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RpcPacket) GetIsRequest() bool {
	if x != nil {
		return x.IsRequest
	}
	return false
}

func (x *RpcPacket) GetTotalPieces() uint32 {
	if x != nil {
		return x.TotalPieces
	}
	return 0
}

func (x *RpcPacket) GetPieceIdx() uint32 {
	if x != nil {
		return x.PieceIdx
	}
	return 0
}

func (x *RpcPacket) GetTraceId() int32 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

func (x *RpcPacket) GetCompressionInfo() *RpcCompressionInfo {
	if x != nil {
		return x.CompressionInfo
	}
	return nil
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{5}
}

type Ipv4Addr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr uint32 `protobuf:"varint,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *Ipv4Addr) Reset() {
	*x = Ipv4Addr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv4Addr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv4Addr) ProtoMessage() {}

func (x *Ipv4Addr) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv4Addr.ProtoReflect.Descriptor instead.
func (*Ipv4Addr) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{6}
}

func (x *Ipv4Addr) GetAddr() uint32 {
	if x != nil {
		return x.Addr
	}
	return 0
}

type SocketAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Ip:
	//	*SocketAddr_Ipv4
	Ip   isSocketAddr_Ip `protobuf_oneof:"ip"`
	Port uint32          `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *SocketAddr) Reset() {
	*x = SocketAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocketAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketAddr) ProtoMessage() {}

func (x *SocketAddr) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketAddr.ProtoReflect.Descriptor instead.
func (*SocketAddr) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{7}
}

func (m *SocketAddr) GetIp() isSocketAddr_Ip {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (x *SocketAddr) GetIpv4() *Ipv4Addr {
	if x, ok := x.GetIp().(*SocketAddr_Ipv4); ok {
		return x.Ipv4
	}
	return nil
}

func (x *SocketAddr) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type isSocketAddr_Ip interface {
	isSocketAddr_Ip()
}

type SocketAddr_Ipv4 struct {
	Ipv4 *Ipv4Addr `protobuf:"bytes,1,opt,name=ipv4,proto3,oneof"`
}

func (*SocketAddr_Ipv4) isSocketAddr_Ip() {}

type PeerFeatureFlag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupportConnListSync bool `protobuf:"varint,5,opt,name=support_conn_list_sync,json=supportConnListSync,proto3" json:"support_conn_list_sync,omitempty"`
	DisableP2P          bool `protobuf:"varint,10,opt,name=disable_p2p,json=disableP2p,proto3" json:"disable_p2p,omitempty"`
}

func (x *PeerFeatureFlag) Reset() {
	*x = PeerFeatureFlag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerFeatureFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerFeatureFlag) ProtoMessage() {}

func (x *PeerFeatureFlag) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerFeatureFlag.ProtoReflect.Descriptor instead.
func (*PeerFeatureFlag) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{8}
}

func (x *PeerFeatureFlag) GetSupportConnListSync() bool {
	if x != nil {
		return x.SupportConnListSync
	}
	return false
}

func (x *PeerFeatureFlag) GetDisableP2P() bool {
	if x != nil {
		return x.DisableP2P
	}
	return false
}

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Part1 uint32 `protobuf:"varint,1,opt,name=part1,proto3" json:"part1,omitempty"`
	Part2 uint32 `protobuf:"varint,2,opt,name=part2,proto3" json:"part2,omitempty"`
	Part3 uint32 `protobuf:"varint,3,opt,name=part3,proto3" json:"part3,omitempty"`
	Part4 uint32 `protobuf:"varint,4,opt,name=part4,proto3" json:"part4,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_etg_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_etg_common_proto_rawDescGZIP(), []int{9}
}

func (x *UUID) GetPart1() uint32 {
	if x != nil {
		return x.Part1
	}
	return 0
}

func (x *UUID) GetPart2() uint32 {
	if x != nil {
		return x.Part2
	}
	return 0
}

func (x *UUID) GetPart3() uint32 {
	if x != nil {
		return x.Part3
	}
	return 0
}

func (x *UUID) GetPart4() uint32 {
	if x != nil {
		return x.Part4
	}
	return 0
}

var File_etg_common_proto protoreflect.FileDescriptor

var file_etg_common_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x74, 0x67, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x0f, 0x65, 0x74, 0x67, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x52, 0x70, 0x63, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x88, 0x01, 0x0a, 0x0a, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41,
	0x0a, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x70, 0x63, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x22, 0x78, 0x0a, 0x0b, 0x52, 0x70,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f,
	0x67, 0x6f, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x55, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x12, 0x52, 0x70, 0x63, 0x43, 0x6f, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a, 0x04, 0x61,
	0x6c, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x65, 0x61, 0x73, 0x79,
	0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f, 0x50, 0x62,
	0x52, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x12, 0x4a, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e,
	0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x6c,
	0x67, 0x6f, 0x50, 0x62, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x41, 0x6c,
	0x67, 0x6f, 0x22, 0x8c, 0x03, 0x0a, 0x09, 0x52, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x50, 0x65, 0x65, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x6f, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x74, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x41, 0x0a,
	0x0a, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x70, 0x63, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x69, 0x65,
	0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x69, 0x65, 0x63, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x69, 0x65, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x69, 0x65, 0x63, 0x65,
	0x49, 0x64, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x51,
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74,
	0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x70,
	0x63, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x08, 0x49, 0x70, 0x76,
	0x34, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x5a, 0x0a, 0x0a, 0x53, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x32, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x34, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72,
	0x5f, 0x67, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x70, 0x76, 0x34, 0x41,
	0x64, 0x64, 0x72, 0x48, 0x00, 0x52, 0x04, 0x69, 0x70, 0x76, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x42,
	0x04, 0x0a, 0x02, 0x69, 0x70, 0x22, 0x67, 0x0a, 0x0f, 0x50, 0x65, 0x65, 0x72, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x33, 0x0a, 0x16, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x79,
	0x6e, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x32, 0x70, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x32, 0x70, 0x22, 0x5e,
	0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x31, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x72, 0x74, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x61, 0x72,
	0x74, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74,
	0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x34, 0x2a, 0x34,
	0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67,
	0x6f, 0x50, 0x62, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x5a, 0x73,
	0x74, 0x64, 0x10, 0x02, 0x2a, 0xb4, 0x01, 0x0a, 0x07, 0x4e, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0c, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x4e, 0x6f, 0x50, 0x41, 0x54, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x75,
	0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x65, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x65, 0x64, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x65, 0x64, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x10, 0x06, 0x12, 0x12, 0x0a, 0x0e, 0x53,
	0x79, 0x6d, 0x55, 0x64, 0x70, 0x46, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x10, 0x07, 0x12,
	0x14, 0x0a, 0x10, 0x53, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x45, 0x61, 0x73, 0x79,
	0x49, 0x6e, 0x63, 0x10, 0x08, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x45, 0x61, 0x73, 0x79, 0x44, 0x65, 0x63, 0x10, 0x09, 0x42, 0x31, 0x5a, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69,
	0x65, 0x72, 0x2f, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_etg_common_proto_rawDescOnce sync.Once
	file_etg_common_proto_rawDescData = file_etg_common_proto_rawDesc
)

func file_etg_common_proto_rawDescGZIP() []byte {
	file_etg_common_proto_rawDescOnce.Do(func() {
		file_etg_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_etg_common_proto_rawDescData)
	})
	return file_etg_common_proto_rawDescData
}

var file_etg_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_etg_common_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_etg_common_proto_goTypes = []interface{}{
	(CompressionAlgoPb)(0),     // 0: easytier_go.common.CompressionAlgoPb
	(NatType)(0),               // 1: easytier_go.common.NatType
	(*RpcDescriptor)(nil),      // 2: easytier_go.common.RpcDescriptor
	(*RpcRequest)(nil),         // 3: easytier_go.common.RpcRequest
	(*RpcResponse)(nil),        // 4: easytier_go.common.RpcResponse
	(*RpcCompressionInfo)(nil), // 5: easytier_go.common.RpcCompressionInfo
	(*RpcPacket)(nil),          // 6: easytier_go.common.RpcPacket
	(*Void)(nil),               // 7: easytier_go.common.Void
	(*Ipv4Addr)(nil),           // 8: easytier_go.common.Ipv4Addr
	(*SocketAddr)(nil),         // 9: easytier_go.common.SocketAddr
	(*PeerFeatureFlag)(nil),    // 10: easytier_go.common.PeerFeatureFlag
	(*UUID)(nil),               // 11: easytier_go.common.UUID
	(*Error)(nil),              // 12: easytier_go.error.Error
}
var file_etg_common_proto_depIdxs = []int32{
	2,  // 0: easytier_go.common.RpcRequest.descriptor:type_name -> easytier_go.common.RpcDescriptor
	12, // 1: easytier_go.common.RpcResponse.error:type_name -> easytier_go.error.Error
	0,  // 2: easytier_go.common.RpcCompressionInfo.algo:type_name -> easytier_go.common.CompressionAlgoPb
	0,  // 3: easytier_go.common.RpcCompressionInfo.accepted_algo:type_name -> easytier_go.common.CompressionAlgoPb
	2,  // 4: easytier_go.common.RpcPacket.descriptor:type_name -> easytier_go.common.RpcDescriptor
	5,  // 5: easytier_go.common.RpcPacket.compression_info:type_name -> easytier_go.common.RpcCompressionInfo
	8,  // 6: easytier_go.common.SocketAddr.ipv4:type_name -> easytier_go.common.Ipv4Addr
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_etg_common_proto_init() }
func file_etg_common_proto_init() {
	if File_etg_common_proto != nil {
		return
	}
	file_etg_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_etg_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCompressionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv4Addr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocketAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerFeatureFlag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_etg_common_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*SocketAddr_Ipv4)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_etg_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_etg_common_proto_goTypes,
		DependencyIndexes: file_etg_common_proto_depIdxs,
		EnumInfos:         file_etg_common_proto_enumTypes,
		MessageInfos:      file_etg_common_proto_msgTypes,
	}.Build()
	File_etg_common_proto = out.File
	file_etg_common_proto_rawDesc = nil
	file_etg_common_proto_goTypes = nil
	file_etg_common_proto_depIdxs = nil
}
