// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.36.1
// source: etg_error.proto

package peerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OtherError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *OtherError) Reset() {
	*x = OtherError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtherError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherError) ProtoMessage() {}

func (x *OtherError) ProtoReflect() protoreflect.Message {
	mi := &file_etg_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherError.ProtoReflect.Descriptor instead.
func (*OtherError) Descriptor() ([]byte, []int) {
	return file_etg_error_proto_rawDescGZIP(), []int{0}
}

func (x *OtherError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type InvalidMethodIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodIndex uint32 `protobuf:"varint,2,opt,name=method_index,json=methodIndex,proto3" json:"method_index,omitempty"`
}

func (x *InvalidMethodIndex) Reset() {
	*x = InvalidMethodIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_error_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidMethodIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidMethodIndex) ProtoMessage() {}

func (x *InvalidMethodIndex) ProtoReflect() protoreflect.Message {
	mi := &file_etg_error_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidMethodIndex.ProtoReflect.Descriptor instead.
func (*InvalidMethodIndex) Descriptor() ([]byte, []int) {
	return file_etg_error_proto_rawDescGZIP(), []int{1}
}

func (x *InvalidMethodIndex) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *InvalidMethodIndex) GetMethodIndex() uint32 {
	if x != nil {
		return x.MethodIndex
	}
	return 0
}

type InvalidService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *InvalidService) Reset() {
	*x = InvalidService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_error_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidService) ProtoMessage() {}

func (x *InvalidService) ProtoReflect() protoreflect.Message {
	mi := &file_etg_error_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidService.ProtoReflect.Descriptor instead.
func (*InvalidService) Descriptor() ([]byte, []int) {
	return file_etg_error_proto_rawDescGZIP(), []int{2}
}

func (x *InvalidService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ProstDecodeError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProstDecodeError) Reset() {
	*x = ProstDecodeError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_error_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProstDecodeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProstDecodeError) ProtoMessage() {}

func (x *ProstDecodeError) ProtoReflect() protoreflect.Message {
	mi := &file_etg_error_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProstDecodeError.ProtoReflect.Descriptor instead.
func (*ProstDecodeError) Descriptor() ([]byte, []int) {
	return file_etg_error_proto_rawDescGZIP(), []int{3}
}

type ProstEncodeError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProstEncodeError) Reset() {
	*x = ProstEncodeError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_error_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProstEncodeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProstEncodeError) ProtoMessage() {}

func (x *ProstEncodeError) ProtoReflect() protoreflect.Message {
	mi := &file_etg_error_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProstEncodeError.ProtoReflect.Descriptor instead.
func (*ProstEncodeError) Descriptor() ([]byte, []int) {
	return file_etg_error_proto_rawDescGZIP(), []int{4}
}

type ExecuteError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ExecuteError) Reset() {
	*x = ExecuteError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_error_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteError) ProtoMessage() {}

func (x *ExecuteError) ProtoReflect() protoreflect.Message {
	mi := &file_etg_error_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteError.ProtoReflect.Descriptor instead.
func (*ExecuteError) Descriptor() ([]byte, []int) {
	return file_etg_error_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type MalformatRpcPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *MalformatRpcPacket) Reset() {
	*x = MalformatRpcPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_error_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MalformatRpcPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MalformatRpcPacket) ProtoMessage() {}

func (x *MalformatRpcPacket) ProtoReflect() protoreflect.Message {
	mi := &file_etg_error_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MalformatRpcPacket.ProtoReflect.Descriptor instead.
func (*MalformatRpcPacket) Descriptor() ([]byte, []int) {
	return file_etg_error_proto_rawDescGZIP(), []int{6}
}

func (x *MalformatRpcPacket) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Timeout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *Timeout) Reset() {
	*x = Timeout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_error_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeout) ProtoMessage() {}

func (x *Timeout) ProtoReflect() protoreflect.Message {
	mi := &file_etg_error_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeout.ProtoReflect.Descriptor instead.
func (*Timeout) Descriptor() ([]byte, []int) {
	return file_etg_error_proto_rawDescGZIP(), []int{7}
}

func (x *Timeout) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ErrorKind:
	//	*Error_OtherError
	//	*Error_InvalidMethodIndex
	//	*Error_InvalidService
	//	*Error_ProstDecodeError
	//	*Error_ProstEncodeError
	//	*Error_ExecuteError
	//	*Error_MalformatRpcPacket
	//	*Error_Timeout
	ErrorKind isError_ErrorKind `protobuf_oneof:"error_kind"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_etg_error_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_etg_error_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_etg_error_proto_rawDescGZIP(), []int{8}
}

func (m *Error) GetErrorKind() isError_ErrorKind {
	if m != nil {
		return m.ErrorKind
	}
	return nil
}

func (x *Error) GetOtherError() *OtherError {
	if x, ok := x.GetErrorKind().(*Error_OtherError); ok {
		return x.OtherError
	}
	return nil
}

func (x *Error) GetInvalidMethodIndex() *InvalidMethodIndex {
	if x, ok := x.GetErrorKind().(*Error_InvalidMethodIndex); ok {
		return x.InvalidMethodIndex
	}
	return nil
}

func (x *Error) GetInvalidService() *InvalidService {
	if x, ok := x.GetErrorKind().(*Error_InvalidService); ok {
		return x.InvalidService
	}
	return nil
}

func (x *Error) GetProstDecodeError() *ProstDecodeError {
	if x, ok := x.GetErrorKind().(*Error_ProstDecodeError); ok {
		return x.ProstDecodeError
	}
	return nil
}

func (x *Error) GetProstEncodeError() *ProstEncodeError {
	if x, ok := x.GetErrorKind().(*Error_ProstEncodeError); ok {
		return x.ProstEncodeError
	}
	return nil
}

func (x *Error) GetExecuteError() *ExecuteError {
	if x, ok := x.GetErrorKind().(*Error_ExecuteError); ok {
		return x.ExecuteError
	}
	return nil
}

func (x *Error) GetMalformatRpcPacket() *MalformatRpcPacket {
	if x, ok := x.GetErrorKind().(*Error_MalformatRpcPacket); ok {
		return x.MalformatRpcPacket
	}
	return nil
}

func (x *Error) GetTimeout() *Timeout {
	if x, ok := x.GetErrorKind().(*Error_Timeout); ok {
		return x.Timeout
	}
	return nil
}

type isError_ErrorKind interface {
	isError_ErrorKind()
}

type Error_OtherError struct {
	OtherError *OtherError `protobuf:"bytes,1,opt,name=other_error,json=otherError,proto3,oneof"`
}

type Error_InvalidMethodIndex struct {
	InvalidMethodIndex *InvalidMethodIndex `protobuf:"bytes,2,opt,name=invalid_method_index,json=invalidMethodIndex,proto3,oneof"`
}

type Error_InvalidService struct {
	InvalidService *InvalidService `protobuf:"bytes,3,opt,name=invalid_service,json=invalidService,proto3,oneof"`
}

type Error_ProstDecodeError struct {
	ProstDecodeError *ProstDecodeError `protobuf:"bytes,4,opt,name=prost_decode_error,json=prostDecodeError,proto3,oneof"`
}

type Error_ProstEncodeError struct {
	ProstEncodeError *ProstEncodeError `protobuf:"bytes,5,opt,name=prost_encode_error,json=prostEncodeError,proto3,oneof"`
}

type Error_ExecuteError struct {
	ExecuteError *ExecuteError `protobuf:"bytes,6,opt,name=execute_error,json=executeError,proto3,oneof"`
}

type Error_MalformatRpcPacket struct {
	MalformatRpcPacket *MalformatRpcPacket `protobuf:"bytes,7,opt,name=malformat_rpc_packet,json=malformatRpcPacket,proto3,oneof"`
}

type Error_Timeout struct {
	Timeout *Timeout `protobuf:"bytes,8,opt,name=timeout,proto3,oneof"`
}

func (*Error_OtherError) isError_ErrorKind() {}

func (*Error_InvalidMethodIndex) isError_ErrorKind() {}

func (*Error_InvalidService) isError_ErrorKind() {}

func (*Error_ProstDecodeError) isError_ErrorKind() {}

func (*Error_ProstEncodeError) isError_ErrorKind() {}

func (*Error_ExecuteError) isError_ErrorKind() {}

func (*Error_MalformatRpcPacket) isError_ErrorKind() {}

func (*Error_Timeout) isError_ErrorKind() {}

var File_etg_error_proto protoreflect.FileDescriptor

var file_etg_error_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x74, 0x67, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x31, 0x0a, 0x0a, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5a, 0x0a, 0x12, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x22, 0x33, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x73,
	0x74, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x12, 0x0a, 0x10,
	0x50, 0x72, 0x6f, 0x73, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x33, 0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x39, 0x0a, 0x12, 0x4d, 0x61, 0x6c, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x52, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x2e, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x85, 0x05, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x40, 0x0a, 0x0b, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x0a, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x59, 0x0a, 0x14,
	0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x65, 0x61, 0x73,
	0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x48, 0x00, 0x52, 0x12, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x4c, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x73, 0x74, 0x5f, 0x64,
	0x65, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67, 0x6f, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x73, 0x74, 0x44, 0x65, 0x63, 0x6f, 0x64,
	0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x73, 0x74, 0x44,
	0x65, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x53, 0x0a, 0x12, 0x70, 0x72,
	0x6f, 0x73, 0x74, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65,
	0x72, 0x5f, 0x67, 0x6f, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x73, 0x74,
	0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x10, 0x70,
	0x72, 0x6f, 0x73, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x46, 0x0a, 0x0d, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65,
	0x72, 0x5f, 0x67, 0x6f, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x59, 0x0a, 0x14, 0x6d, 0x61, 0x6c, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x5f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72,
	0x5f, 0x67, 0x6f, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x4d, 0x61, 0x6c, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x52, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x00, 0x52, 0x12,
	0x6d, 0x61, 0x6c, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x67,
	0x6f, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x48,
	0x00, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x2f,
	0x65, 0x61, 0x73, 0x79, 0x74, 0x69, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_etg_error_proto_rawDescOnce sync.Once
	file_etg_error_proto_rawDescData = file_etg_error_proto_rawDesc
)

func file_etg_error_proto_rawDescGZIP() []byte {
	file_etg_error_proto_rawDescOnce.Do(func() {
		file_etg_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_etg_error_proto_rawDescData)
	})
	return file_etg_error_proto_rawDescData
}

var file_etg_error_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_etg_error_proto_goTypes = []interface{}{
	(*OtherError)(nil),         // 0: easytier_go.error.OtherError
	(*InvalidMethodIndex)(nil), // 1: easytier_go.error.InvalidMethodIndex
	(*InvalidService)(nil),     // 2: easytier_go.error.InvalidService
	(*ProstDecodeError)(nil),   // 3: easytier_go.error.ProstDecodeError
	(*ProstEncodeError)(nil),   // 4: easytier_go.error.ProstEncodeError
	(*ExecuteError)(nil),       // 5: easytier_go.error.ExecuteError
	(*MalformatRpcPacket)(nil), // 6: easytier_go.error.MalformatRpcPacket
	(*Timeout)(nil),            // 7: easytier_go.error.Timeout
	(*Error)(nil),              // 8: easytier_go.error.Error
}
var file_etg_error_proto_depIdxs = []int32{
	0, // 0: easytier_go.error.Error.other_error:type_name -> easytier_go.error.OtherError
	1, // 1: easytier_go.error.Error.invalid_method_index:type_name -> easytier_go.error.InvalidMethodIndex
	2, // 2: easytier_go.error.Error.invalid_service:type_name -> easytier_go.error.InvalidService
	3, // 3: easytier_go.error.Error.prost_decode_error:type_name -> easytier_go.error.ProstDecodeError
	4, // 4: easytier_go.error.Error.prost_encode_error:type_name -> easytier_go.error.ProstEncodeError
	5, // 5: easytier_go.error.Error.execute_error:type_name -> easytier_go.error.ExecuteError
	6, // 6: easytier_go.error.Error.malformat_rpc_packet:type_name -> easytier_go.error.MalformatRpcPacket
	7, // 7: easytier_go.error.Error.timeout:type_name -> easytier_go.error.Timeout
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_etg_error_proto_init() }
func file_etg_error_proto_init() {
	if File_etg_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_etg_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtherError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_error_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidMethodIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_error_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_error_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProstDecodeError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_error_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProstEncodeError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_error_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_error_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MalformatRpcPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_error_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timeout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_etg_error_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_etg_error_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Error_OtherError)(nil),
		(*Error_InvalidMethodIndex)(nil),
		(*Error_InvalidService)(nil),
		(*Error_ProstDecodeError)(nil),
		(*Error_ProstEncodeError)(nil),
		(*Error_ExecuteError)(nil),
		(*Error_MalformatRpcPacket)(nil),
		(*Error_Timeout)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_etg_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_etg_error_proto_goTypes,
		DependencyIndexes: file_etg_error_proto_depIdxs,
		MessageInfos:      file_etg_error_proto_msgTypes,
	}.Build()
	File_etg_error_proto = out.File
	file_etg_error_proto_rawDesc = nil
	file_etg_error_proto_goTypes = nil
	file_etg_error_proto_depIdxs = nil
}
